# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# jekyll serve --host $IP --port $PORT --baseurl ''
host: 127.0.0.1

port: 4000

# Site settings
title:
  en: Dashyx
  fr: Dashyx
email: contact@dashyx.com
index:
  en: en
  fr: fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dashyx.com" # the base hostname & protocol for your site
cover: ""
logo: ""

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: ""

